host: "0.0.0.0"
port: 5678

logging:
  log_dir: "logs"

cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

users_json_path: "database/users.json"

environment_variables:
  - "secret_key"
  - "db_password"

user_data_settings:
  length:
    nickname: [3, 32]
    password: [8, 128]
  requirements:
    password:
      uppercase: true
      lowercase: true
      digit: true
      special_char: true
  regex:
    email: "[^@]+@[^@]+\\.[^@]+"
    special_chars: "[!@#$%^&*(),.?\":{}|<>]"

load_dotenv: true
debug: false

mobile_network_data:
  data_dir: "database/mobile_network_data"
  file_extension: ".txt"
  default_page: 1
  default_count: 100
  max_count: 1000

database:
  host: "94.159.111.243"
  port: "5432"
  name: "mobile_data"
  user: "mobile_data_user"
  password: ""